first release
IlyaKhalizov/golang-united-lectures pull request #1
Opened 2022-11-01 13:54 UTC by ivangurin

2022-11-02 08:01 UTC, RealJimy requested changes

2022-11-02 18:52 UTC, ivangurin commented on api/proto/lecture.proto
> +   string CreatedBy = 1;
Переделал имена полей в камел кейс.

2022-11-02 18:53 UTC, ivangurin commented on cmd/main.go
> +	db_name := os.Getenv("LECTURES_DB_NAME")
По нему нужно сначала разобраться как она работает. Предлагаю оставить на развитие. Пока пусть так будет.

2022-11-02 19:02 UTC, ivangurin commented on cmd/main.go
> +	s := grpc.NewServer()
Переименовал переменные.

2022-11-02 19:05 UTC, ivangurin commented on cmd/main.go
> +	l, err := net.Listen("tcp", ":8080")
Переименовал переменные. Вынес порт в константу. Думаю что порт работы сервера можно не выносить в переменные окружения, т.к. он будет работать в каком то контейнере и потом будет мапиться на другой порт.

2022-11-02 19:08 UTC, ivangurin commented on internal/database/database.go
> +	dsn := "host=" + host + " port=" + port + " user=" + user + " password=" + password + " database=" + name + " sslmode=disable TimeZone=Europe/Moscow"
Передела на fmt.Sprintf

2022-11-02 19:26 UTC, ivangurin commented on internal/database/database.go
> +
Пустые строки между получением ошибки и проверкой на ошибки убрал. Со всеми остальными пустыми строками мне удобнее код читать. Когда пустых строк нет - для меня это ад.

2022-11-02 19:36 UTC, ivangurin commented on internal/lecture/lecture.go
> +		err = errors.New("lecture is deleted")
Переделал возврат ошибок на специальный статус.

2022-11-02 19:37 UTC, ivangurin commented on internal/lecture/lecture.go
> +		return nil, err
Везде переделал на возврат статусной ошибки.

2022-11-02 19:40 UTC, ivangurin commented on internal/lecture/lecture.go
> +		lercureResponse.Description = lecture.Description
Так и сделал.

2022-11-02 19:55 UTC, ivangurin commented on api/proto/lecture.proto
> +   string CourseId = 1;
Добавил в запрос флаг при установке которого будут показываться удаленные. А также добавил параметры для лимита и офсета.

2022-11-02 20:34 UTC, ivangurin commented on internal/lecture/lecture.go
> +		return nil, err
Сделал печать реальных ошибок в лог и возврат нейтральной ошибки.

2022-11-02 20:36 UTC, ivangurin commented on internal/lecture/lecture.go
> +			continue
Добавил в параметры запроса параметр showDeleted и если он не установлен, то делаю фильтр записей бд по условию IS NULL.

2022-11-02 20:37 UTC, ivangurin commented on internal/lecture/lecture.go
> +	response := &api.GetListResponse{}
Так и сделал.

2022-11-02 20:39 UTC, ivangurin commented on internal/lecture/lecture.go
> +		response.Lectures = append(response.Lectures, &lercureResponse)
Это относится к предыдущему замечанию. Так и сделал.

2022-11-02 20:42 UTC, ivangurin commented on internal/lecture/lecture.go
> +		if !lecture.DeletedAt.IsZero() {
Сейчас я переделал на параметр показывать удаленные или нет с фильтром сразу из БД. Соответственно если будут удаленные, то сюда уже код дойдет.

2022-11-02 20:47 UTC, ivangurin commented on internal/models/lecture.go
> +	lecture.CreatedAt = time.Now()
Уберу заполнение. Посмотрю заполнит он сам или нет.

2022-11-02 20:48 UTC, ivangurin commented on internal/lecture/lecture.go
> +	lecture.ChangedAt = time.Now()
Переименовал поле. Также проверю заполняет он его сам или нет.

2022-11-02 20:59 UTC, ivangurin commented on internal/models/lecture.go
> +	err := db.Client.Model(l).Select("count(*) > 0").Where("id = ?", l.Id).Find(&exists).Error
Немного переделал. Был один метод Save. Заменил его разные методы Create, Update и Delete для большей явности.

2022-11-03 20:22 UTC, RealJimy requested changes

2022-11-03 20:22 UTC, RealJimy commented on internal/lecture/lecture.go
> +package lecture
Путь лучше заменить на internal/services/lecture.go
Смысл в том, что если/когда будет расширятся функционал, то чтобы не плодить отдельные каталоги под каждый сервис, все будут в одном месте. Т.е. структура должна быть по аналогии с internal/models/lecture.go где в одном каталоге могут храниться разные модели.

2022-11-03 20:22 UTC, RealJimy commented on internal/models/lecture.go
> +package models
Илья предложил переименовать каталог `models` в `repositories` (т.е. должно быть ./internal/repositories/lecture.go)т.к. это лучше отражает суть пакета сожержащего помимо модели еще и методы для работы с данными. Я не понял этой разницы, предлагаю просто переименовать.

2022-11-03 20:22 UTC, RealJimy commented on internal/lecture/lecture.go
> +		// if !lecture.UpdatedAt.IsZero() {
Совет. Не оставляй закомментированные куски. В этом нет смысла, но засоряет код. Если это временно и ты предполагаешь, что это потом нужно будет вернуть, то история изменений есть в гите - всегда можно достать из истории, то что было раньше на этом месте.

2022-11-03 20:22 UTC, RealJimy commented on internal/database/database.go
> +package database
Пакет нужно перенести из `internal` в `pkg` т.к. это не бизнес логика приложения, а то что потенциально можно переиспользовать.

2022-11-03 20:26 UTC, RealJimy commented on internal/models/lecture.go
> +	lecture.CreatedAt = time.Now()
Ну что, заполняет?

2022-11-05 18:56 UTC, ivangurin commented on internal/models/lecture.go
> +	lecture.CreatedAt = time.Now()
Да, заполняет. При создании заполняет сразу два поля и created_at и updated_at. Не знаю насколько это правильно. Есть еще специальный тип для поля deleted_at. Если его указать то горм сам будет его проставлять при удалении записи, а не удалять запись. Но при этом он не обновляет другие поля. Я сделал, что бы при операциях CUD хаб мог заполнить ид пользователя, который делает эту операцию. И в случае удаления горм просто обновляет поля с временем удаления. Поэтому я сам обновляю время и проставляю код пользователя при удалении.

2022-11-05 19:20 UTC, ivangurin commented on cmd/main.go
> +	dbName := os.Getenv("LECTURES_DB_NAME")
Перенес настройки в отдельные пакет.

2022-11-05 19:21 UTC, ivangurin commented on internal/lecture/lecture.go
> +		if !lecture.CreatedAt.IsZero() {
Да и UpdatedAt тоже. Так горм работает. Поправил код - убрал проверки для на IsZero для этих полей

2022-11-05 19:23 UTC, ivangurin commented on internal/lecture/lecture.go
> +package lecture
Заменил.

2022-11-05 19:24 UTC, ivangurin commented on internal/models/lecture.go
> +package models
models так красиво звучит :(

2022-11-05 19:25 UTC, ivangurin commented on internal/models/lecture.go
> +package models
Но все равно переименовал.

2022-11-05 19:26 UTC, ivangurin commented on internal/lecture/lecture.go
> +		// if !lecture.UpdatedAt.IsZero() {
Я забыл раскомментировать после эксперимента с датами. Расскомментировал. Условие это тут нужно.

2022-11-05 19:35 UTC, ivangurin commented on internal/database/database.go
> +package database
Перенес.

2022-12-13 22:04 UTC, merged